Update LINUX_Shell_Scripting

diff --git a/LINUX_Shell_Scripting b/LINUX_Shell_Scripting
--- a/LINUX_Shell_Scripting
+++ b/LINUX_Shell_Scripting
@@ -8,3 +8,17 @@ Basically it returns error code as out put
 0 ->Successful 
 1 ->
 2 ->
+
+Shell Script:-
+ #!/bin/bash
+
+cat file.txt 
+
+if [ $? -eq 0 ]
+then
+  echo "The script ran ok"
+  exit 0
+else
+  echo "The script failed" >&2
+  exit 1
+fi
